name: Custom Workflow

on:
  workflow_dispatch:

jobs:
  custom_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print custom message
        run: echo "Custom workflow running successfully!"

