name: Dependency Updates

on:
  schedule:
    - cron: '0 10 * * 0'  # Weekly on Sunday at 10 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Dependabot config
        run: |
          mkdir -p .github
          cat > .github/dependabot.yml << EOF
          version: 2
          updates:
            - package-ecosystem: "npm"
              directory: "/"
              schedule:
                interval: "weekly"
              open-pull-requests-limit: 10
            - package-ecosystem: "github-actions"
              directory: "/"
              schedule:
                interval: "weekly"
          EOF
      - name: Run Dependabot (via script simulation)
        run: gh pr create --title "Dependency Update" --body "Automated update" || echo "PR creation simulated"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

