name: Scheduled Tasks
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  maintenance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Daily task backup - $(date)" > backup.log
      - uses: actions/upload-artifact@v4
        with:
          name: backup-log
          path: backup.log
